<table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
    <thead>
        <tr>
            <!--Non de colonne -->
            <th>Positionnement</th>
            <th>Nunéro Projet</th>
            <th>Nom Projet</th>
            <th>Description</th>
            <th>Lien Image</th>
            <th>Éditer</th>
            <th>Effacr</th>

        </tr>
    </thead>
    <tbody>
        <?php
        // fait la liste des projet en les appelant la requete verif_projet dans  project.php
        $compter = 0;
        while ($get_projet = $verif_projet->fetch(PDO::FETCH_ASSOC)) {
            $compter++ ?>
            <tr>
                <!--Affiche les valeur appeller par la boucle while juste en haut 1 par 1 -->
                <td width="20"><?php echo $compter ?></td>
                <td><?php echo $get_projet['num_projet'] ?></td>
                <td><?php echo $get_projet['nom'] ?></td>
                <td><?php echo $get_projet['description'] ?></td>
                <td><a href="<?php echo $get_projet['lien']; ?>" </a><?php echo $get_projet['lien']; ?></td>
                <td>
                    <center><a href="project_edit.php?num_projet=<?php echo $get_projet['num_projet']; ?>"><button class="btn btn-primary btn-xs">Éditer</button></a></center>
                </td>
                <td>
                    <center><a onclick="return confirm('Voulez Vous Réelement Supprimer le Projet ?')" href="project.php?num_projet=<?php echo $get_projet['num_projet']; ?>&supr_projet=ok"><button class="btn btn-danger btn-xs">Supprimer</button></a></center>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>