<div class="contenant">
  <img src="https://img.static-rmg.be/a/view/q75/w/h/2130037/cactus-fleur-1008588991-jpg.jpg" alt="image" />
  <div class="texte_centrer">
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum sint harum nesciunt rerum tempora perspiciatis maxime sunt earum quisquam eos placeat, tenetur asperiores porro ipsam quaerat exercitationem quibusdam explicabo. Provident.</p>

  </div>

  <p id="txt2">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum sint harum nesciunt rerum tempora perspiciatis maxime sunt earum quisquam eos placeat, tenetur asperiores porro ipsam quaerat exercitationem quibusdam explicabo. Provident.</p>
  <p id="txt3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum sint harum nesciunt rerum tempora perspiciatis maxime sunt earum quisquam eos placeat, tenetur asperiores porro ipsam quaerat exercitationem quibusdam explicabo. Provident.</p>

</div>