<div class="bg">
    <section class="bg1" aria-label="Photos">
    </section>
    <section class="bg2">
        <div class="accueil-txt-div">
            <div class="accueil-txt accueil-txt-1">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo culpa sed ad animi molestiae esse voluptate aliquid ex laborum optio? Necessitatibus porro cupiditate modi sequi, voluptatem vero voluptas tempore hic!
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate totam voluptatibus quo ipsam laboriosam eligendi facilis, repellendus laborum deserunt facere quia praesentium harum fugiat nulla nobis tempora. Ex, quas et.
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quam saepe et, sit delectus ab adipisci minus aliquam ex sint eaque ipsam vero voluptate officia quisquam omnis recusandae reiciendis non nobis.
                </p>
            </div>
            <div class="accueil-txt accueil-txt-2">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo culpa sed ad animi molestiae esse voluptate aliquid ex laborum optio? Necessitatibus porro cupiditate modi sequi, voluptatem vero voluptas tempore hic!
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum aperiam officiis temporibus eligendi ipsam repellat unde, ullam ipsa et nulla dolore velit assumenda neque a quibusdam. Exercitationem pariatur culpa labore?
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui adipisci eaque distinctio illum delectus! Ipsam, nostrum at fugit repellat praesentium maiores deleniti, placeat soluta minima mollitia repudiandae porro, voluptates aspernatur.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam magnam consequatur animi veritatis accusamus dolor neque voluptatum iure quod quaerat eum reiciendis laudantium laborum ab perferendis expedita, tempora porro dignissimos!
                </p>
            </div>
            <div class="accueil-txt accueil-txt-3">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo culpa sed ad animi molestiae esse voluptate aliquid ex laborum optio? Necessitatibus porro cupiditate modi sequi, voluptatem vero voluptas tempore hic!
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati fugiat est mollitia eaque in, laboriosam sit similique nemo, maxime, ratione autem corrupti maiores placeat voluptas atque rem consectetur impedit recusandae.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt accusantium unde accusamus neque nostrum officiis quisquam, perspiciatis doloribus natus dicta ratione sapiente, tempora aut quis quos cupiditate ipsam sed maxime!
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestias, qui nihil, totam quas distinctio doloremque in veritatis, pariatur numquam asperiores nostrum laboriosam tempore? Nulla id vitae optio commodi a quas.
                </p>
            </div>
        </div>
    </section>
</div>