<form action="project.php" method="POST">

    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Numero Projet <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="text" id="num_projet" name="num_projet" value="<?php echo $get_projet['num_projet'] ?>" class="form-control col-md-7 col-xs-12">
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nom <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" id="nom" name="nom" value="<?php echo $get_projet['nom'] ?>" class="form-control col-md-7 col-xs-12">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Projet lien <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" id="lien" name="lien" value="<?php echo $get_projet['lien'] ?>" class="form-control col-md-7 col-xs-12">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Projet description <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" id="description" name="description" value="<?php echo $get_projet['description'] ?>" class="form-control col-md-7 col-xs-12">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Projet description <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <input name="num_projet" value="<?php echo $get_projet['num_projet'] ?>" class=" form-control col-md-7 col-xs-12">
            </div>
        </div>
    </div>
    <div class="ln_solid"></div>
    <div class="form-group">
        <div align="left" class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
            <!-- name="num_projet" va dans project.php et de la elle enregistre la donnée dans la BDD -->
            <button type="submit" name="num_projet" class="btn btn-success">Enregistrer </button>
        </div>
    </div>
</form>